


export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const UPDATE_PURCHASABLE = 'UPDATE_PURCHASABLE'


export const RESET_INGREDIENTS = 'RESET_INGREDIENTS'

export const LOAD_ORDERS = 'LOAD_ORDERS'
export const ORDER_LOAD_FAILED = 'ORDER_LOAD_FAILED'
export const ORDER_LOADING = 'ORDER_LOADING'


export const PLACE_ORDER = 'PLACE_ORDER'
export const PLACING_ORDER = 'PLACING_ORDER'
export const PLACE_ORDER_FAILED = 'PLACE_ORDER_FAILED'
